services:
  integraciones-client:
    image: integraciones-client
    container_name: integraciones-client
    user: "1001:1001"
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - coco-network
    volumes:
      - ./credentials:/home/coco/app/credentials

networks:
  coco-network:
    external: true
